ignVarNames =
(
\bAHKcode2\b
\bAHKcodeMsgBox\b
\bAHKcode\b
\bALinfoOnleyNEW\b
\bALinfoOnley\b
\bA_AhkPath\b
\bA_AhkVersion\b
\bA_Args\b
\bA_CaretX\b
\bA_CaretY\b
\bA_ComputerName\b
\bA_DD\b
\bA_FormatInteger\b
\bA_GuiX\b
\bA_Hour\b
\bA_IconHidden\b
\bA_Index\b
\bA_Is64bitOS\b
\bA_IsAdmin\b
\bA_IsCompiled\b
\bA_IsUnicode\b
\bA_LastError\b
\bA_LineFile\b
\bA_LineNumber\b
\bA_LoopField\b
\bA_LoopReadLine\b
\bA_MM\b
\bA_MSec\b
\bA_Min\b
\bA_Now\b
\bA_PriorKey\b
\bA_ProgramFiles\b
\bA_PtrSize\b
\bA_SPACE\b
\bA_ScreenDPI\b
\bA_ScreenHeight\b
\bA_ScreenWidth\b
\bA_ScriptDir\b
\bA_ScriptFullPath\b
\bA_ScriptName\b
\bA_Sec\b
\bA_SendLevel\b
\bA_StringCaseSense\b
\bA_Tab\b
\bA_ThisFunc\b
\bA_ThisLabel\b
\bA_TickCount\b
\bA_TimeIdleKeyboard\b
\bA_TimeIdlePhysical\b
\bA_TimeIdle\b
\bA_TimeSincePriorHotkey\b
\bA_WorkingDir\b
\bA_YYYY\b
\bClipboardAll\b
\bCollection\b
\bDBA\b
\bErrorLevel\b
\bFOUNDmyselfCounter\b
\bFileExist1\b
\bFileExist2\b
\bHardDriveLetter\b
\bIfMsgBox\b
\bLast_A_This\b
\bListBoxPosX\b
\bListBoxPosY\b
\bMemoryBuffer\b
\bModiTime\b
\bModiTime_OLD\b
\bMySQL_ExternDir\b
\bParseWordsCount\b
\bRegReadActionList_DebugInfo\b
\bSELECTactionListmodified\b
\bScriptHwnd\b
\bScriptNameLetter2\b
\bScriptNameLetter\b
\bSingleMatchAllStr\b
\bSingleMatchCount\b
\bSleepBeforeRundIfExist\b
\bSql_Temp\b
\bStartTime\b
\bStuff\b
\bTTS\b
\bWordsTbl\b
\b_ArchLoggerCallBack\b
\b_ArchLoggerFile\b
\b_Struct\b
\b_max_size\b
\b_uix_\b
\bactionListActive\b
\bactionListDirBase\b
\bactionListDirBase\b
\bactionListDir\b
\bactionListDir\b
\bactionListFileName\b
\bactionListFilterPath2Abs\b
\bactionListFilterPath2\b
\bactionListFilterPathNEW\b
\bactionListFilterPathNEWdir\b
\bactionListFilterPath\b
\bactionListLastModified\b
\bactionListLastSize\b
\bactionListModiTime\b
\bactionListModiTime_OLD\b
\bactionListModified\b
\bactionListNEW\b
\bactionListNEW\b
\bactionListNewTemp_RAW\b
\bactionListNewTemp_withoutExt\b
\bactionListOLD\b
\bactionListReg\b
\bactionListSHORT\b
\bactionListWithoutGenerated_withExt\b
\b actionList\b
\b actionList\b
\bactionList_inClassFolder_Exist\b
\bactionList_isNotAProject\b
\bactionList_isNotAProject_withoutExt\b
\bactionList_withExt\b
\bactionListsize\b
\bactiveClassOLD\b
\bactiveClass\b
\bactiveClass\b
\bactiveTitleOLD\b
\bactiveTitle\b
\bactiveTitle\b
\bactiveTitle_short\b
\bahkCode1\b
\bahkSourceTemp\b
\bahkSource\b
\balClass\b
\balControl\b
\balTitle\b
\bat\b
\bbackup_g_min_searchWord_length\b
\bbaseDir\b
\bblank\b
\bc\b
\bclilpboard\b
\bclipboard\b
\bcomspec\b
\bconfigContentNew\b
\bconfigContent\b
\bconfigContentminify\b
\bconfigIncAhkAddress\b
\bconfigMinifyIncAhkAddressSTATIC\b
\bconfigMinifyIncAhkAddress\b
\bconfigMinifyIncAhkContentSTATIC\b
\bconfigMinifyIncAhkContent\b
\bconfigMinifyObj\b
\bcontrolNameOLD\b
\bcontrolName\b
\bcontrolName\b
\bcopyCTriggeredTimeMilli\b
\bcountNotchangingActiveTitleOLD\b
\bdebugIt\b
\bdemoTestData\b
\bdft_ArrowKeyMethod\b
\bdft_AutoSpace\b
\bdft_DetectMouseClickMove\b
\bdft_DisabledAutoCompleteKeys\b
\bdft_DoNotLearnStrings\b
\bdft_EndWordCharacters\b
\bdft_ExcludeProgramExecutables\b
\bdft_ExcludeProgramTitles\b
\bdft_ForceNewWordCharacters\b
\bdft_HelperWindowProgramExecutables\b
\bdft_HelperWindowProgramTitles\b
\bdft_IncludeProgramExecutables\b
\bdft_IncludeProgramTitles\b
\bdft_LearnCount\b
\bdft_LearnLength\b
\bdft_LearnMode\b
\bdft_Length\b
\bdft_ListBoxCharacterWidth\b
\bdft_ListBoxFontFixed\b
\bdft_ListBoxFontOverride\b
\bdft_ListBoxFontSize\b
\bdft_ListBoxMaxWidth\b
\bdft_ListBoxNotDPIAwareProgramExecutables\b
\bdft_ListBoxOffSet\b
\bdft_ListBoxOpacity\b
\bdft_ListBoxRows\b
\bdft_NoBackSpace\b
\bdft_NumPresses\b
\bdft_SendMethod\b
\bdft_ShowLearnedFirst\b
\bdft_SuppressMatchingWord\b
\bdft_TerminatingCharacters\b
\bdiffMilli\b
\bdoReadActionListTXTfileSTR\b
\bdoReadActionListTXTfile\b
\bdoReadThisActionListEverySeconds\b
\bdo_tooltipReadActionList\b
\be\b
\beach\b
\belapsedMilli\b
\belapsedSec\b
\berrorMsg\b
\berrorsLog\b
\bexe\b
\bextension\b
\bfalse\b
\bfeedbackMsgBox1PosBackup_x\b
\bfeedbackMsgBox1PosBackup_y\b
\bfeedback\b
\bfileAddress_flag\b
\bfileExist\b
\bfileExist_class_actionListFilter\b
\bfilterFileName\b
\bfirstLine\b
\bfnReceive_actionListAddress\b
\bfoundPos\b
\bgDBA_ADO\b
\bgDBA_ArchLogger\b
\bgDBA_Exceptions\b
\bgDBA_MySQL_Field\b
\bgDBA_SQLiteDataType\b
\bgDBA_null\b
\bg_Active_Id\b
\bg_Active_Pid\b
\bg_Active_Process\b
\bg_Active_Title\b
\bg_CaretX_Old\b
\bg_CaretX_selectWord\b
\bg_CaretY_Old\b
\bg_CaretY_selectWord\b
\bg_DelimiterChar\b
\bg_DpiAware\b
\bg_DpiScalingFactor\b
\bg_EVENT_SYSTEM_FOREGROUND\b
\bg_EVENT_SYSTEM_SCROLLINGEND\b
\bg_EVENT_SYSTEM_SCROLLINGSTART\b
\bg_EnabledKeyboardHotKeys\b
\bg_FLAGmsgbox\b
\bg_GCLP_HCURSOR\b
\bg_HelperClosedWindowIds\b
\bg_HelperManual\b
\bg_Helper_Id\b
\bg_IDC_HAND\b
\bg_IDC_HELP\b
\bg_IMAGE_CURSOR\b
\bg_IgnoreSend\b
\bg_LR_SHARED\b
\bg_LastActiveIdBeforeHelper\b
\bg_LastInput_Id\b
\bg_LegacyLearnedWords\b
\bg_ListBox10\b
\bg_ListBox1\b
\bg_ListBox2\b
\bg_ListBox3\b
\bg_ListBox4\b
\bg_ListBox5\b
\bg_ListBox6\b
\bg_ListBox7\b
\bg_ListBox8\b
\bg_ListBox9\b
\bg_ListBoxActualSizeH_maxFound\b
\bg_ListBoxCharacterWidthComputed\b
\bg_ListBoxContentWidth\b
\bg_ListBoxFlipped\b
\bg_ListBoxFontSize\b
\bg_ListBoxHwnd10\b
\bg_ListBoxHwnd1\b
\bg_ListBoxHwnd2\b
\bg_ListBoxHwnd3\b
\bg_ListBoxHwnd4\b
\bg_ListBoxHwnd5\b
\bg_ListBoxHwnd6\b
\bg_ListBoxHwnd7\b
\bg_ListBoxHwnd8\b
\bg_ListBoxHwnd9\b
\bg_ListBoxMaxWordHeight\b
\bg_ListBoxOffsetComputed\b
\bg_ListBoxPosX\b
\bg_ListBoxPosY\b
\bg_ListBoxScrollCallback\b
\bg_ListBoxTitle\b
\bg_ListBoxTitle_firstTimeInMilli\b
\bg_ListBoxX\b
\bg_ListBoxX_old\b
\bg_ListBoxY\b
\bg_ListBoxY_old\b
\bg_ListBox_Id\b
\bg_ManualActivate\b
\bg_MatchLongestLength\b
\bg_MatchPos\b
\bg_MatchStart\b
\bg_MatchTotal\b
\bg_Match\b
\bg_MouseWin_Id\b
\bg_NULL\b
\bg_NormalizationKD\b
\bg_NumKeyMethod\b
\bg_OSVersion\b
\bg_OldCaretX\b
\bg_OldCaretY\b
\bg_OldMatchStart\b
\bg_OldMatch\b
\bg_OriginalMatchStart\b
\bg_PID\b
\bg_PROCESS_QUERY_INFORMATION\b
\bg_PROCESS_QUERY_LIMITED_INFORMATION\b
\bg_PauseState\b
\bg_PrefsFile\b
\bg_PrefsSections\b
\bg_Process_DPI_Unaware\b
\bg_Process_Per_Monitor_DPI_Aware\b
\bg_Process_System_DPI_Aware\b
\bg_SB_VERT\b
\bg_SIF_POS\b
\bg_SM_CMONITORS\b
\bg_SM_CXFOCUSBORDER\b
\bg_SM_CXVSCROLL\b
\bg_ScriptTitle\b
\bg_ScrollEventHookThread\b
\bg_ScrollEventHook\b
\bg_SetClassLongFunction\b
\bg_SingleMatchDescription\b
\bg_SingleMatchReplacement\b
\bg_SingleMatch\b
\bg_StartTime_TickCountMilli\b
\bg_TerminatingCharactersParsed\b
\bg_TerminatingEndKeys\b
\bg_TimeMilli_SincePriorMouseClick\b
\bg_WINEVENT_SKIPOWNPROCESS\b
\bg_WM_LBUTTONDBLCLK\b
\bg_WM_LBUTTONUP\b
\bg_WM_MOUSEMOVE\b
\bg_WM_SETCURSOR\b
\bg_WinChangedCallback\b
\bg_WinChangedEventHook\b
\bg_Word\b
\bg_XYSaved\b
\bg_XY\b
\bg_actionListDB\b
\bg_actionListDBfileAdress\b
\bg_actionListDone\b
\bg_actionListID\b
\bg_actionList_UsedByUser_since_midnight\b
\bg_activeClassOLD\b
\bg_activeTitleOLD\b
\bg_config\b
\bg_cursor_hand\b
\bg_doAskBevoreChangingActionList\b
\bg_doListBoxFollowMouse\b
\bg_doRunLogFiles\b
\bg_doSaveLogFiles\b
\bg_doSound\b
\bg_doUseSendPlay\b
\bg_feedbackMsgBoxNr\b
\bg_fontColor\b
\bg_ignReg\b
\bg_ignReg_exampleUsing\b
\bg_inSettings\b
\bg_isEnabledKeyboardHotKeys\b
\bg_isListBoxDisabled\b
\bg_is_correct_list_found\b
\bg_itsProbablyArecentUpdate\b
\bg_lineNumberFeedback\b
\bg_listSELECT_FROM_WinTitle\b
\bg_method\b
\bg_minBytesNeedetToAskBevoreChangingActionList\b
\bg_min_MonitorBound_right\b
\bg_min_searchWord_length\b
\bg_min_searchWord_length_2\b
\bg_nextCriticalCommandString\b
\bg_nextCriticalCommandTimeIdle\b
\bg_permanentSELECT\b
\bg_permanentSELECT_OLD\b
\bg_permanentSELECT_type\b
\bg_regExReplaceInVisibleLine\b
\bg_reloadIf_ListBox_Id_notExist\b
\bg_sending_is_buggy\b
\bg_show_ListBox_Id_EMTY_COUNT\b
\bg_ttSpeakObject\b
\bhelloWelcomeMessage\b
\bhelpinfo_ArrowKeyMethod\b
\bhelpinfo_AutoSpace\b
\bhelpinfo_DetectMouseClickMove\b
\bhelpinfo_DisabledAutoCompleteKeys\b
\bhelpinfo_DoNotLearnStrings\b
\bhelpinfo_EndWordCharacters\b
\bhelpinfo_ExcludeProgramExecutables\b
\bhelpinfo_ExcludeProgramTitles\b
\bhelpinfo_ForceNewWordCharacters\b
\bhelpinfo_FullHelpString\b
\bhelpinfo_HelperWindowProgramExecutables\b
\bhelpinfo_HelperWindowProgramTitles\b
\bhelpinfo_IncludeProgramExecutables\b
\bhelpinfo_IncludeProgramTitles\b
\bhelpinfo_LearnCount\b
\bhelpinfo_LearnLength\b
\bhelpinfo_LearnMode\b
\bhelpinfo_Length\b
\bhelpinfo_ListBoxCharacterWidth\b
\bhelpinfo_ListBoxFontFixed\b
\bhelpinfo_ListBoxFontOverride\b
\bhelpinfo_ListBoxFontSize\b
\bhelpinfo_ListBoxMaxWidth\b
\bhelpinfo_ListBoxNotDPIAwareProgramExecutables\b
\bhelpinfo_ListBoxOffset\b
\bhelpinfo_ListBoxOpacity\b
\bhelpinfo_ListBoxRows\b
\bhelpinfo_NoBackSpace\b
\bhelpinfo_NumPresses\b
\bhelpinfo_SendMethod\b
\bhelpinfo_ShowLearnedFirst\b
\bhelpinfo_SuppressMatchingWord\b
\bhelpinfo_TerminatingCharacters\b
\bi\b
\biconAdress\b
\binc17032207130\b
\binc1703220730\b
\bincModiTime\b
\bincModiTime_OLD\b
\binfoText\b
\bisActuallyWrittenToLog\b
\bisInIn\b
\bisMultiline\b
\bisRegListChanged\b
\bisSizeChanged\b
\bisSizeNull\b
\bisSlowMotion\b
\bisTimeChanged\b
\bis_AL_without_fileName\b
\bis_codeRunner_exist\b
\bis_create_found\b
\bitsProbablyNewInstallation\b
\blang\b
\blbl_default_checkActionListAHKfile_sizeAndModiTime\b
\blineFileName\b
\blineNumberFrom\b
\blistBoxFontSizeOLD\b
\blll\b
\blogFileName\b
\blog\b
\bmNew\b
\bm\b
\bmatch\b
\bmatchs\b
\bmaxLinesOfCode4length1\b
\bmilliSinceLastRegistryUpdate\b
\bmilliSinceLastRegistryUpdate_sec\b
\bmilliesTried_getNewListFromRegistry\b
\bmillis_since_midnight\b
\bmin\b
\bmod\b
\bmouseClass\b
\bmouseControl\b
\bmouseID\b
\bmouseTitle\b
\bmouseX\b
\bmouseY\b
\bmsg\b
\bmsg\b
\bmvarInjectsAHKcode\b
\bname\b
\bnewFontSize\b
\bnowWinGetClass\b
\bpId\b
\bprefs_ArrowKeyMethod\b
\bprefs_AutoSpace\b
\bprefs_DetectMouseClickMove\b
\bprefs_DisabledAutoCompleteKeys\b
\bprefs_DoNotLearnStrings\b
\bprefs_EndWordCharacters\b
\bprefs_ExcludeProgramExecutables\b
\bprefs_ExcludeProgramTitles\b
\bprefs_ForceNewWordCharacters\b
\bprefs_HelperWindowProgramExecutables\b
\bprefs_HelperWindowProgramTitles\b
\bprefs_IncludeProgramExecutables\b
\bprefs_IncludeProgramTitles\b
\bprefs_LearnCount\b
\bprefs_LearnLength\b
\bprefs_LearnMode\b
\bprefs_ListBoxCharacterWidth\b
\bprefs_ListBoxFontFixed\b
\bprefs_ListBoxFontOverride\b
\bprefs_ListBoxFontSize\b
\bprefs_ListBoxMaxWidth\b
\bprefs_ListBoxNotDPIAwareProgramExecutables\b
\bprefs_ListBoxOffset\b
\bprefs_ListBoxOpacity\b
\bprefs_ListBoxRows\b
\bprefs_NoBackSpace\b
\bprefs_NumPresses\b
\bprefs_SendMethod\b
\bprefs_ShowLearnedFirst\b
\bprefs_SuppressMatchingWord\b
\bprefs_TerminatingCharacters\b
\bregExPattern\b
\bresult\b
\breturn_from_LineNumber\b
\brow\b
\brunCount\b
\brunnerAddress\b
\bsActionListFileName\b
\bsActionListWithoutGenerated_withExt\b
\bs\b
\bscriptNameWithoutAHK\b
\bscriptName\b
\bshort_RegReadActionList_DebugInfo\b
\bshort_actionList\b
\bsimulateAfirstUserContact\b
\bsourceDir\b
\bspeakedLastActionList\b
\bsqlLastError\b
\bsql_template_dir\b
\bstop_list_change\b
\bstop_list_change\b
\bstrDebugByRef\b
\bt\b
\btempFileAddress\b
\btemp\b
\btemp\b
\btest\b
\bthisLine\b
\btimeFirstTry_getNewListFromRegistry\b
\btimeoutSec\b
\btimestampyyMMddHHmmssPretty\b
\btimestampyyMMddHHmmss\b
\btip\b
\btitle\b
\btodo\b
\btoolTipGui_yOffsetNr\b
\btoolTipGui_yOffsetNr\b
\btooltipPosY\b
\btrue\b
\bupdatedTimeStamp_millisSinceMidnight\b
\bwb\b
\bx\b
)